"""
OpenGreenWave-India: ESP32 MicroPython Firmware
This script synchronizes the ESP32 internal RTC with GPS atomic time and 
controls traffic light LEDs to maintain a continuous Green Wave based on 
a pre-calculated offset.
"""

from machine import Pin, UART, RTC
import time
import json

# --- HARDWARE CONFIGURATION ---
# GPS UART (NEO-6M typically uses 9600 baud)
GPS_TX_PIN = 17 # Connect to GPS RX
GPS_RX_PIN = 16 # Connect to GPS TX
gps_uart = UART(1, baudrate=9600, tx=GPS_TX_PIN, rx=GPS_RX_PIN)

# Traffic Light GPIO Pins (Simulating Relays)
RED_PIN = 25
YELLOW_PIN = 26
GREEN_PIN = 27

red_led = Pin(RED_PIN, Pin.OUT)
yellow_led = Pin(YELLOW_PIN, Pin.OUT)
green_led = Pin(GREEN_PIN, Pin.OUT)

rtc = RTC()

# --- GLOBALS ---
# These would typically be loaded from config.json generated by greenwave_calc.py
CONFIG_OFFSET_S = 36  # Calculated offset in seconds for this specific junction
BASE_CYCLE_S = 60     # Total time for a full Red-Yellow-Green cycle
GREEN_DURATION_S = 30 # How long the light stays green

def load_config():
    """Attempt to load configuration from config.json if available."""
    global CONFIG_OFFSET_S, BASE_CYCLE_S
    try:
        with open('config.json', 'r') as f:
            config = json.load(f)
            CONFIG_OFFSET_S = config['green_wave_config']['calculated_offset_s']
            BASE_CYCLE_S = config['green_wave_config']['base_cycle_s']
            print(f"Loaded config: Offset={CONFIG_OFFSET_S}s, Cycle={BASE_CYCLE_S}s")
    except Exception as e:
        print("Using default configuration.")

def parse_gps_time():
    """
    Reads NMEA sentences from UART, looks for $GPRMC to extract UTC time,
    and updates the ESP32 RTC. 
    Returns True if time synced successfully, False otherwise.
    """
    if gps_uart.any():
        try:
            line = gps_uart.readline().decode('utf-8')
            # Look for Recommended Minimum Specific GPS/Transit Data
            if line.startswith('$GPRMC'):
                parts = line.split(',')
                # Check if data is valid (V = invalid, A = active)
                if len(parts) > 2 and parts[2] == 'A':
                    time_str = parts[1] # Format: HHMMSS.SS
                    date_str = parts[9] # Format: DDMMYY
                    
                    if time_str and date_str:
                        hh = int(time_str[0:2])
                        mm = int(time_str[2:4])
                        ss = int(time_str[4:6])
                        
                        day = int(date_str[0:2])
                        month = int(date_str[2:4])
                        year = 2000 + int(date_str[4:6])
                        
                        # Set internal RTC (Year, Month, Day, Weekday, Hours, Minutes, Seconds, Subseconds)
                        # Note: This is UTC time.
                        rtc.datetime((year, month, day, 0, hh, mm, ss, 0))
                        print(f"RTC Synced with GPS: {year}-{month:02d}-{day:02d} {hh:02d}:{mm:02d}:{ss:02d} UTC")
                        return True
        except Exception as e:
            # Silently handle UART decode errors which are common with raw GPS data
            pass
    return False

def set_traffic_light(state):
    """Sets the LED states. State can be 'RED', 'YELLOW', or 'GREEN'."""
    if state == 'RED':
        red_led.value(1)
        yellow_led.value(0)
        green_led.value(0)
    elif state == 'YELLOW':
        red_led.value(0)
        yellow_led.value(1)
        green_led.value(0)
    elif state == 'GREEN':
        red_led.value(0)
        yellow_led.value(0)
        green_led.value(1)

def run_traffic_loop():
    """
    Main loop that checks atomic time against the offset and triggers lights.
    """
    print("Starting OpenGreenWave Traffic Loop...")
    
    # Yellow light duration before turning red
    YELLOW_DURATION_S = 3
    
    while True:
        # Get current time from RTC
        # rtc.datetime() returns (year, month, day, weekday, hours, minutes, seconds, subseconds)
        dt = rtc.datetime()
        current_ss = dt[6] # seconds
        current_mm = dt[5] # minutes
        
        # Calculate absolute time in seconds for synchronization purposes
        # We synchronize based on the minute to keep it simple, but in reality 
        # it would sync based on a specific epoch or hour to ensure all 
        # junctions share the exact same 'zero' reference point.
        absolute_time_s = (current_mm * 60) + current_ss
        
        # Where are we in the local cycle?
        # Subtract the offset to mathematically "shift" this junction's cycle
        shifted_time_s = (absolute_time_s - CONFIG_OFFSET_S) % BASE_CYCLE_S
        
        # Determine Light State
        if shifted_time_s < GREEN_DURATION_S:
            set_traffic_light('GREEN')
        elif shifted_time_s < (GREEN_DURATION_S + YELLOW_DURATION_S):
            set_traffic_light('YELLOW')
        else:
            set_traffic_light('RED')
            
        # Try to sync GPS time periodically in the background
        parse_gps_time()
        
        time.sleep(0.1)

def main():
    # Turn all lights off initially
    red_led.value(0)
    yellow_led.value(0)
    green_led.value(0)
    
    load_config()
    
    print("Waiting for GPS Time Sync...")
    synced = False
    while not synced:
        synced = parse_gps_time()
        # Blink yellow while waiting for GPS lock
        set_traffic_light('YELLOW')
        time.sleep(0.5)
        set_traffic_light('RED')
        time.sleep(0.5)
        
    # Start the synchronized loop
    run_traffic_loop()

if __name__ == '__main__':
    main()
