"""
OpenGreenWave-India: ESP32 MicroPython Firmware
This script synchronizes the ESP32 internal RTC with GPS atomic time and 
controls traffic light LEDs to maintain a continuous Green Wave based on 
a pre-calculated offset.
"""

from machine import Pin, UART, RTC
import time
import json

# --- HARDWARE CONFIGURATION ---
# GPS UART (NEO-6M typically uses 9600 baud)
GPS_TX_PIN = 17 # Connect to GPS RX
GPS_RX_PIN = 16 # Connect to GPS TX
gps_uart = UART(1, baudrate=9600, tx=GPS_TX_PIN, rx=GPS_RX_PIN)

# Traffic Light GPIO Pins (Simulating Relays)
RED_PIN = 25
YELLOW_PIN = 26
GREEN_PIN = 27

red_led = Pin(RED_PIN, Pin.OUT)
yellow_led = Pin(YELLOW_PIN, Pin.OUT)
green_led = Pin(GREEN_PIN, Pin.OUT)

rtc = RTC()

# --- GLOBALS ---
# These would typically be loaded from config.json generated by greenwave_calc.py
CONFIG_OFFSET_S = 36  # Calculated offset in seconds for this specific junction
BASE_CYCLE_S = 60     # Total time for a full Red-Yellow-Green cycle
GREEN_DURATION_S = 30 # How long the light stays green

def load_config():
    """Attempt to load configuration from config.json if available."""
    global CONFIG_OFFSET_S, BASE_CYCLE_S
    try:
        with open('config.json', 'r') as f:
            config = json.load(f)
            CONFIG_OFFSET_S = config['green_wave_config']['calculated_offset_s']
            BASE_CYCLE_S = config['green_wave_config']['base_cycle_s']
            print(f"Loaded config: Offset={CONFIG_OFFSET_S}s, Cycle={BASE_CYCLE_S}s")
    except Exception:
        print("Using default configuration.")

def parse_gprmc(line):
    """
    Pure parsing of a single $GPRMC NMEA sentence. Returns a
    (year, month, day, hh, mm, ss) tuple if the sentence carries a valid
    ('A') fix, or None otherwise. Kept separate from the RTC/UART calls
    below so it can be unit-tested on a desktop Python interpreter without
    real hardware.
    """
    if not line.startswith('$GPRMC'):
        return None

    parts = line.split(',')
    # Check if data is valid (V = invalid, A = active)
    if len(parts) <= 9 or parts[2] != 'A':
        return None

    time_str = parts[1]  # Format: HHMMSS.SS
    date_str = parts[9]  # Format: DDMMYY

    if not time_str or not date_str:
        return None

    hh = int(time_str[0:2])
    mm = int(time_str[2:4])
    ss = int(time_str[4:6])

    day = int(date_str[0:2])
    month = int(date_str[2:4])
    year = 2000 + int(date_str[4:6])

    return (year, month, day, hh, mm, ss)


def parse_gps_time():
    """
    Reads NMEA sentences from UART, looks for $GPRMC to extract UTC time,
    and updates the ESP32 RTC.
    Returns True if time synced successfully, False otherwise.
    """
    if gps_uart.any():
        try:
            line = gps_uart.readline().decode('utf-8')
            parsed = parse_gprmc(line)
            if parsed:
                year, month, day, hh, mm, ss = parsed
                # Set internal RTC (Year, Month, Day, Weekday, Hours, Minutes, Seconds, Subseconds)
                # Note: This is UTC time.
                rtc.datetime((year, month, day, 0, hh, mm, ss, 0))
                print(f"RTC Synced with GPS: {year}-{month:02d}-{day:02d} {hh:02d}:{mm:02d}:{ss:02d} UTC")
                return True
        except Exception:
            # Silently handle UART decode errors which are common with raw GPS data
            pass
    return False

def set_traffic_light(state):
    """Sets the LED states. State can be 'RED', 'YELLOW', or 'GREEN'."""
    if state == 'RED':
        red_led.value(1)
        yellow_led.value(0)
        green_led.value(0)
    elif state == 'YELLOW':
        red_led.value(0)
        yellow_led.value(1)
        green_led.value(0)
    elif state == 'GREEN':
        red_led.value(0)
        yellow_led.value(0)
        green_led.value(1)

# Yellow light duration before turning red
YELLOW_DURATION_S = 3


def calculate_light_state(hh, mm, ss, offset_s, base_cycle_s,
                           green_duration_s, yellow_duration_s):
    """
    Pure function: given the current time-of-day and this junction's
    Green Wave configuration, returns 'GREEN', 'YELLOW', or 'RED'.
    Kept separate from the RTC/GPIO calls so it can be unit-tested on a
    desktop Python interpreter without real hardware.

    Uses seconds-since-midnight (not just seconds-since-the-hour) as the
    time base. An earlier version used only (minutes * 60 + seconds),
    which reset to 0 at the top of every hour - for any base_cycle_s that
    doesn't evenly divide 3600, that reset caused a real synchronization
    glitch once per hour, since the "shifted" cycle position jumped
    instead of continuing smoothly. Seconds-since-midnight only has that
    same discontinuity once every 24 hours instead of every hour (see
    README Known Limitations for why this isn't fully eliminated).
    """
    absolute_time_s = (hh * 3600) + (mm * 60) + ss

    # Where are we in the local cycle?
    # Subtract the offset to mathematically "shift" this junction's cycle
    shifted_time_s = (absolute_time_s - offset_s) % base_cycle_s

    if shifted_time_s < green_duration_s:
        return 'GREEN'
    elif shifted_time_s < (green_duration_s + yellow_duration_s):
        return 'YELLOW'
    else:
        return 'RED'


def run_traffic_loop():
    """
    Main loop that checks atomic time against the offset and triggers lights.
    """
    print("Starting OpenGreenWave Traffic Loop...")

    while True:
        # rtc.datetime() returns (year, month, day, weekday, hours, minutes, seconds, subseconds)
        dt = rtc.datetime()
        state = calculate_light_state(
            dt[4], dt[5], dt[6],
            CONFIG_OFFSET_S, BASE_CYCLE_S,
            GREEN_DURATION_S, YELLOW_DURATION_S,
        )
        set_traffic_light(state)

        # Try to sync GPS time periodically in the background
        parse_gps_time()

        time.sleep(0.1)

def main():
    # Turn all lights off initially
    red_led.value(0)
    yellow_led.value(0)
    green_led.value(0)
    
    load_config()
    
    print("Waiting for GPS Time Sync...")
    synced = False
    while not synced:
        synced = parse_gps_time()
        # Blink yellow while waiting for GPS lock
        set_traffic_light('YELLOW')
        time.sleep(0.5)
        set_traffic_light('RED')
        time.sleep(0.5)
        
    # Start the synchronized loop
    run_traffic_loop()

if __name__ == '__main__':
    main()
